version: '3'

services:
  nginx:
    image: php:8.0-apache
    volumes:
      - ./:/var/www/
    ports:
      - "8082:4052"
    container_name: api-my-spa-store

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: api-my-spa-store-app
